/**
 * /api/signals — Active trading signals generated by CoreIntent agents.
 *
 * Returns DEMO signals until agents are live on the Cloudzy VPS (COR-20).
 * Only signals at or above minConfidence are surfaced to the UI.
 * SOL/USD short is intentionally below minConfidence — shown for transparency.
 *
 * Rate limit: 60 req/min (see RATE_LIMITS.default in lib/api.ts)
 */
import { ok, preflight } from "@/lib/api";

interface Signal {
  id: number;
  pair: string;
  direction: "long" | "short";
  /** 0–1 confidence score. Only signals >= minConfidence are actionable. */
  confidence: number;
  source: string;
  timestamp: string;
}

interface SignalsResponse {
  /** Filtered to signals >= minConfidence. */
  signals: Signal[];
  minConfidence: number;
  totalActive: number;
  totalPending: number;
  mode: "demo" | "live";
}

const MIN_CONFIDENCE = 0.75;

const ALL_SIGNALS: Signal[] = [
  { id: 1, pair: "BTC/USD", direction: "long",  confidence: 0.87, source: "TrendFollower", timestamp: new Date().toISOString() },
  { id: 2, pair: "ETH/USD", direction: "long",  confidence: 0.79, source: "MeanRevert",    timestamp: new Date().toISOString() },
  { id: 3, pair: "SOL/USD", direction: "short", confidence: 0.62, source: "SentimentBot",  timestamp: new Date().toISOString() },
];

export async function GET() {
  const data: SignalsResponse = {
    signals: ALL_SIGNALS.filter((s) => s.confidence >= MIN_CONFIDENCE),
    minConfidence: MIN_CONFIDENCE,
    totalActive: 12,
    totalPending: 3,
    mode: "demo",
  };
  return ok(data);
}

export async function OPTIONS() {
  return preflight();
}
