/**
 * /api/signals — Active trading signals generated by CoreIntent agents.
 *
 * Returns DEMO signals until agents are live on the Cloudzy VPS (COR-20).
 * Only signals at or above minConfidence are surfaced to the UI.
 * SOL/USD short is intentionally below minConfidence — shown for transparency.
 *
 * Rate limit: 60 req/min (see RATE_LIMITS.default in lib/api.ts)
 */
import { ok, preflight, serverError } from "@/lib/api";

interface Signal {
  id:         number;
  pair:       string;
  direction:  "long" | "short";
  /** 0–1 confidence score. Only signals >= minConfidence are actionable. */
  confidence: number;
  source:     string;
  timestamp:  string;
}

/** Template without timestamp — stamped fresh at request time in GET. */
interface SignalTemplate {
  id:         number;
  pair:       string;
  direction:  "long" | "short";
  confidence: number;
  source:     string;
}

interface SignalsResponse {
  /** Filtered to signals >= minConfidence. */
  signals:       Signal[];
  minConfidence: number;
  /** Count of signals at or above minConfidence. */
  totalActive:   number;
  /** Count of signals below minConfidence (low-confidence, not surfaced). */
  totalPending:  number;
  mode:          "demo" | "live";
  timestamp:     string;
}

const MIN_CONFIDENCE = 0.75;

/**
 * Static signal definitions. Timestamps are stamped per-request in GET
 * to avoid serving stale module-load timestamps after long uptimes.
 */
const SIGNAL_TEMPLATES: SignalTemplate[] = [
  { id: 1, pair: "BTC/USD", direction: "long",  confidence: 0.87, source: "TrendFollower" },
  { id: 2, pair: "ETH/USD", direction: "long",  confidence: 0.79, source: "MeanRevert"    },
  { id: 3, pair: "SOL/USD", direction: "short", confidence: 0.62, source: "SentimentBot"  },
];

export async function GET() {
  try {
    const now = new Date().toISOString();
    const allSignals: Signal[] = SIGNAL_TEMPLATES.map((t) => ({ ...t, timestamp: now }));

    const data: SignalsResponse = {
      signals:       allSignals.filter((s) => s.confidence >= MIN_CONFIDENCE),
      minConfidence: MIN_CONFIDENCE,
      totalActive:   allSignals.filter((s) => s.confidence >= MIN_CONFIDENCE).length,
      totalPending:  allSignals.filter((s) => s.confidence <  MIN_CONFIDENCE).length,
      mode:          "demo",
      timestamp:     now,
    };
    return ok(data);
  } catch (e) {
    return serverError(e);
  }
}

export async function OPTIONS() {
  return preflight();
}
