/**
 * /api/signals — Active trading signals generated by CoreIntent agents.
 *
 * Returns DEMO signals until agents are live on the Cloudzy VPS (COR-20).
 * By default only signals at or above minConfidence are surfaced to the UI.
 * SOL/USD short is intentionally below the default threshold — shown for transparency.
 *
 * Query params:
 *   ?minConfidence=0.8  — override the default 0.75 threshold (0–1, float).
 *   ?pair=BTC%2FUSD     — filter to a single trading pair.
 *
 * Rate limit: 60 req/min (see RATE_LIMITS.default in lib/api.ts)
 */
import { NextRequest } from "next/server";
import { demoOk, badRequest, preflight, serverError, checkRateLimit, tooManyRequests } from "@/lib/api";

interface Signal {
  id:         number;
  pair:       string;
  direction:  "long" | "short";
  /** 0–1 confidence score. Only signals >= minConfidence are actionable. */
  confidence: number;
  source:     string;
  timestamp:  string;
}

/** Template without timestamp — stamped fresh at request time in GET. */
interface SignalTemplate {
  id:         number;
  pair:       string;
  direction:  "long" | "short";
  confidence: number;
  source:     string;
}

interface SignalsResponse {
  /** Filtered to signals >= effective minConfidence. */
  signals:       Signal[];
  minConfidence: number;
  /** Count of signals at or above minConfidence. */
  totalActive:   number;
  /** Count of signals below minConfidence (low-confidence, not surfaced). */
  totalPending:  number;
  mode:          "demo" | "live";
  timestamp:     string;
}

const DEFAULT_MIN_CONFIDENCE = 0.75;

/**
 * Static signal definitions. Timestamps are stamped per-request in GET
 * to avoid serving stale module-load timestamps after long uptimes.
 */
const SIGNAL_TEMPLATES: readonly SignalTemplate[] = [
  { id: 1, pair: "BTC/USD", direction: "long",  confidence: 0.87, source: "TrendFollower" },
  { id: 2, pair: "ETH/USD", direction: "long",  confidence: 0.79, source: "MeanRevert"    },
  { id: 3, pair: "SOL/USD", direction: "short", confidence: 0.62, source: "SentimentBot"  },
];

export async function GET(req: NextRequest) {
  const ip = req.headers.get("x-forwarded-for") ?? "anon";
  const limit = await checkRateLimit(ip);
  if (limit.limited) return tooManyRequests(limit.retryAfter ?? 60);
  try {
    // ?minConfidence override — must be a finite float in [0, 1].
    const mcParam = req.nextUrl.searchParams.get("minConfidence");
    let minConfidence = DEFAULT_MIN_CONFIDENCE;
    if (mcParam !== null) {
      const parsed = parseFloat(mcParam);
      if (!Number.isFinite(parsed) || parsed < 0 || parsed > 1) {
        return badRequest("minConfidence must be a number between 0 and 1");
      }
      minConfidence = parsed;
    }

    // ?pair filter — exact match against pair strings (e.g. "BTC/USD").
    const pairParam = req.nextUrl.searchParams.get("pair")?.toUpperCase().trim();

    const now = new Date().toISOString();
    let allSignals: Signal[] = SIGNAL_TEMPLATES.map((t) => ({ ...t, timestamp: now }));

    if (pairParam) {
      allSignals = allSignals.filter((s) => s.pair === pairParam);
    }

    const signals = allSignals.filter((s) => s.confidence >= minConfidence);

    const data: SignalsResponse = {
      signals,
      minConfidence,
      totalActive:  signals.length,
      totalPending: allSignals.length - signals.length,
      mode:         "demo",
      timestamp:    now,
    };
    return demoOk(data);
  } catch (e) {
    return serverError(e);
  }
}

export async function OPTIONS() {
  return preflight();
}
