#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# CoreIntent — VPS Lens (Decoder / Rewire / Mirror)
# Run from project root: ./scripts/vps-lens.sh
#
# What it does:
# 1. Connects to VPS, catalogs everything
# 2. Finds wallets, keys, state files
# 3. Checks what's running vs dead
# 4. Pulls state files for AI handover
# 5. Creates a mirror backup locally
# 6. Generates LENS_REPORT.md
#
# Requires: SSH access to VPS
# ═══════════════════════════════════════════════════════════════

set -e

VPS_HOST="${VPS_HOST:-100.122.99.34}"
VPS_USER="${VPS_USER:-root}"
VPS_PASS="${VPS_PASS:-}"
MIRROR_DIR="vps_mirror_$(date +%Y%m%d_%H%M%S)"
REPORT="LENS_REPORT.md"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${CYAN}═══════════════════════════════════════════${NC}"
echo -e "${CYAN} VPS LENS — Decoder / Rewire / Mirror${NC}"
echo -e "${CYAN} Target: ${VPS_USER}@${VPS_HOST}${NC}"
echo -e "${CYAN}═══════════════════════════════════════════${NC}"
echo ""

# Determine SSH method
SSH_CMD=""
SCP_CMD=""
if [ -n "$VPS_PASS" ]; then
  if ! command -v sshpass &> /dev/null; then
    echo -e "${YELLOW}Installing sshpass...${NC}"
    if command -v apt-get &> /dev/null; then
      sudo apt-get install -y sshpass 2>/dev/null
    elif command -v brew &> /dev/null; then
      brew install hudochenkov/sshpass/sshpass 2>/dev/null
    fi
  fi
  SSH_CMD="sshpass -p '$VPS_PASS' ssh -o ConnectTimeout=15 -o StrictHostKeyChecking=no -o PubkeyAuthentication=no ${VPS_USER}@${VPS_HOST}"
  SCP_CMD="sshpass -p '$VPS_PASS' scp -o ConnectTimeout=15 -o StrictHostKeyChecking=no -o PubkeyAuthentication=no"
else
  SSH_CMD="ssh -o ConnectTimeout=15 ${VPS_USER}@${VPS_HOST}"
  SCP_CMD="scp -o ConnectTimeout=15"
fi

# Test connection
echo -e "${BLUE}[1/8] Testing SSH connection...${NC}"
if eval "$SSH_CMD 'echo connected'" 2>/dev/null; then
  echo -e "${GREEN}Connected.${NC}"
else
  echo -e "${RED}Cannot connect to ${VPS_HOST}${NC}"
  echo "Set VPS_PASS env var or ensure SSH key auth works:"
  echo "  VPS_PASS=yourpass ./scripts/vps-lens.sh"
  echo "  OR"
  echo "  ssh-copy-id ${VPS_USER}@${VPS_HOST}"
  exit 1
fi

# Start report
cat > "$REPORT" << HEADER
# VPS Lens Report
**Target:** ${VPS_USER}@${VPS_HOST}
**Date:** $(date)
**Generated by:** vps-lens.sh

HEADER

# Create mirror directory
mkdir -p "$MIRROR_DIR"

# ═══════════════════════════════════════════
# 2. FILE CATALOG
# ═══════════════════════════════════════════
echo -e "${BLUE}[2/8] Cataloging all files...${NC}"

eval "$SSH_CMD" '
echo "## File Catalog"
echo ""
echo "### Total Files"
find /root -type f 2>/dev/null | wc -l
echo ""
echo "### By Extension (top 30)"
echo "| Count | Extension |"
echo "|-------|-----------|"
find /root -type f 2>/dev/null | sed "s/.*\.//" | sort | uniq -c | sort -rn | head -30 | while read count ext; do
  echo "| $count | .$ext |"
done
echo ""
echo "### Disk Usage"
du -sh /root/ 2>/dev/null
echo ""
echo "### Directory Tree (depth 3)"
echo "```"
find /root -maxdepth 3 -type d 2>/dev/null | head -120
echo "```"
' >> "$REPORT" 2>/dev/null

echo -e "${GREEN}File catalog done.${NC}"

# ═══════════════════════════════════════════
# 3. WALLET & KEY FINDER
# ═══════════════════════════════════════════
echo -e "${BLUE}[3/8] Searching for wallets, keys, credentials...${NC}"

echo "" >> "$REPORT"
echo "## Wallet & Credential Search" >> "$REPORT"
echo "" >> "$REPORT"

eval "$SSH_CMD" '
echo "### Wallet Files"
find /root -iname "*wallet*" -o -iname "*keystore*" -o -iname "*.key" -o -iname "*private*key*" -o -iname "*seed*" -o -iname "*mnemonic*" 2>/dev/null | head -30
echo ""
echo "### .env Files"
find /root -name ".env" -o -name ".env.*" -o -name "*.env" 2>/dev/null | head -20
echo ""
echo "### Config Files with Potential Keys"
find /root -name "config.json" -o -name "credentials*" -o -name "secrets*" 2>/dev/null | head -20
echo ""
echo "### Files Containing Key Patterns"
echo "(Searching for API key patterns, wallet addresses, private keys...)"
grep -rl "0x[a-fA-F0-9]\{40\}" /root --include="*.json" --include="*.env" --include="*.txt" --include="*.md" --include="*.ts" --include="*.js" 2>/dev/null | head -20
echo ""
grep -rl "sk-ant-\|xai-\|pplx-\|AKIA\|ghp_\|ghu_\|sk_live\|pk_live" /root --include="*.json" --include="*.env" --include="*.txt" --include="*.md" --include="*.ts" --include="*.js" 2>/dev/null | head -20
' >> "$REPORT" 2>/dev/null

echo -e "${GREEN}Wallet/key search done.${NC}"

# ═══════════════════════════════════════════
# 4. RUNNING SERVICES
# ═══════════════════════════════════════════
echo -e "${BLUE}[4/8] Checking running services...${NC}"

echo "" >> "$REPORT"
echo "## Running Services" >> "$REPORT"
echo "" >> "$REPORT"

eval "$SSH_CMD" '
echo "### Systemd Services (active)"
systemctl list-units --type=service --state=active 2>/dev/null | head -30
echo ""
echo "### Node/Python Processes"
ps aux | grep -E "node|python|tsx|ts-node|npm" | grep -v grep 2>/dev/null
echo ""
echo "### Listening Ports"
ss -tlnp 2>/dev/null || netstat -tlnp 2>/dev/null
echo ""
echo "### Docker Containers"
docker ps 2>/dev/null || echo "(docker not running or not installed)"
echo ""
echo "### Cron Jobs"
crontab -l 2>/dev/null || echo "(no crontab)"
echo ""
echo "### PM2 Processes"
pm2 list 2>/dev/null || echo "(pm2 not installed)"
echo ""
echo "### Nginx/Caddy Sites"
ls /etc/nginx/sites-enabled/ 2>/dev/null || echo "(no nginx)"
ls /etc/caddy/ 2>/dev/null || echo "(no caddy)"
' >> "$REPORT" 2>/dev/null

echo -e "${GREEN}Service check done.${NC}"

# ═══════════════════════════════════════════
# 5. STATE FILES — PULL FOR AI HANDOVER
# ═══════════════════════════════════════════
echo -e "${BLUE}[5/8] Pulling state files for AI handover...${NC}"

echo "" >> "$REPORT"
echo "## State Files (Pulled)" >> "$REPORT"
echo "" >> "$REPORT"

STATE_FILES=(
  "/root/zynthio/SESSION_STATE.md"
  "/root/zynthio/MASTER_HANDOVER.md"
  "/root/zynthio/TODO_MASTER_LIVE.md"
  "/root/zynthio/MCIVOR_FAMILY_TREE.md"
  "/root/zynthio/COREY_WORDS.md"
)

mkdir -p "$MIRROR_DIR/state"

for f in "${STATE_FILES[@]}"; do
  fname=$(basename "$f")
  if eval "$SCP_CMD ${VPS_USER}@${VPS_HOST}:$f $MIRROR_DIR/state/" 2>/dev/null; then
    SIZE=$(ls -lh "$MIRROR_DIR/state/$fname" 2>/dev/null | awk '{print $5}')
    echo -e "${GREEN}Pulled: $fname ($SIZE)${NC}"
    echo "- $fname — $SIZE" >> "$REPORT"
  else
    echo -e "${YELLOW}Not found: $fname${NC}"
    echo "- $fname — NOT FOUND" >> "$REPORT"
  fi
done

# Also pull all .env files
echo "" >> "$REPORT"
echo "### .env Files Pulled" >> "$REPORT"
mkdir -p "$MIRROR_DIR/env"
eval "$SSH_CMD 'find /root -name \".env\" -o -name \".env.*\" 2>/dev/null'" 2>/dev/null | while read envfile; do
  fname=$(echo "$envfile" | tr '/' '_')
  eval "$SCP_CMD ${VPS_USER}@${VPS_HOST}:$envfile $MIRROR_DIR/env/$fname" 2>/dev/null
  echo "- $envfile" >> "$REPORT"
done

echo -e "${GREEN}State files pulled.${NC}"

# ═══════════════════════════════════════════
# 6. RECENT CHANGES
# ═══════════════════════════════════════════
echo -e "${BLUE}[6/8] Finding recent changes (last 7 days)...${NC}"

echo "" >> "$REPORT"
echo "## Recent Changes (last 7 days)" >> "$REPORT"
echo "" >> "$REPORT"

eval "$SSH_CMD" '
echo "```"
find /root -type f -mtime -7 2>/dev/null | head -80
echo "```"
echo ""
echo "### Most Recently Modified (last 24h)"
echo "```"
find /root -type f -mtime -1 2>/dev/null | head -40
echo "```"
' >> "$REPORT" 2>/dev/null

echo -e "${GREEN}Recent changes cataloged.${NC}"

# ═══════════════════════════════════════════
# 7. MIRROR KEY DIRECTORIES
# ═══════════════════════════════════════════
echo -e "${BLUE}[7/8] Mirroring key files...${NC}"

echo "" >> "$REPORT"
echo "## Mirror Contents" >> "$REPORT"
echo "" >> "$REPORT"

# Pull key markdown files
mkdir -p "$MIRROR_DIR/docs"
eval "$SSH_CMD 'find /root/zynthio -maxdepth 1 -name \"*.md\" -type f 2>/dev/null'" 2>/dev/null | while read mdfile; do
  eval "$SCP_CMD ${VPS_USER}@${VPS_HOST}:$mdfile $MIRROR_DIR/docs/" 2>/dev/null
done

# Pull key config/json files
mkdir -p "$MIRROR_DIR/config"
for cfg in package.json tsconfig.json docker-compose.yml Dockerfile; do
  eval "$SCP_CMD ${VPS_USER}@${VPS_HOST}:/root/zynthio/$cfg $MIRROR_DIR/config/" 2>/dev/null
done

# Count what we got
MIRROR_COUNT=$(find "$MIRROR_DIR" -type f 2>/dev/null | wc -l)
MIRROR_SIZE=$(du -sh "$MIRROR_DIR" 2>/dev/null | awk '{print $1}')
echo "- Files mirrored: $MIRROR_COUNT" >> "$REPORT"
echo "- Mirror size: $MIRROR_SIZE" >> "$REPORT"
echo "- Mirror location: $MIRROR_DIR/" >> "$REPORT"

echo -e "${GREEN}Mirror complete: $MIRROR_COUNT files ($MIRROR_SIZE)${NC}"

# ═══════════════════════════════════════════
# 8. HEALTH SUMMARY
# ═══════════════════════════════════════════
echo -e "${BLUE}[8/8] Generating health summary...${NC}"

echo "" >> "$REPORT"
echo "## Health Summary" >> "$REPORT"
echo "" >> "$REPORT"

eval "$SSH_CMD" '
echo "### System"
echo "- Uptime: $(uptime -p 2>/dev/null || uptime)"
echo "- Disk: $(df -h / | tail -1 | awk "{print \$3\"/\"\$2\" used (\" \$5 \")\"}")"
echo "- Memory: $(free -h | grep Mem | awk "{print \$3\"/\"\$2\" used\"}")"
echo "- CPU: $(nproc) cores"
echo "- OS: $(cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d= -f2 | tr -d \")"
echo ""
echo "### Network"
echo "- Public IP: $(curl -s ifconfig.me 2>/dev/null || echo unknown)"
echo "- SSH Port: $(grep -E "^Port " /etc/ssh/sshd_config 2>/dev/null | awk "{print \$2}" || echo 22)"
echo ""
echo "### Security"
echo "- Failed SSH attempts (last 100 lines): $(grep -c "Failed password" /var/log/auth.log 2>/dev/null || echo "N/A")"
echo "- Root login: $(grep "^PermitRootLogin" /etc/ssh/sshd_config 2>/dev/null || echo "default")"
echo "- Firewall: $(ufw status 2>/dev/null | head -1 || echo "ufw not installed")"
' >> "$REPORT" 2>/dev/null

echo -e "${GREEN}Health summary done.${NC}"

# Final summary
echo "" >> "$REPORT"
echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "## Amnesia Shield" >> "$REPORT"
echo "" >> "$REPORT"
echo "To restore context for any AI session, point it to:" >> "$REPORT"
echo "1. \`$MIRROR_DIR/state/SESSION_STATE.md\` — current session state" >> "$REPORT"
echo "2. \`$MIRROR_DIR/state/MASTER_HANDOVER.md\` — full project context" >> "$REPORT"
echo "3. \`$MIRROR_DIR/state/TODO_MASTER_LIVE.md\` — active task list" >> "$REPORT"
echo "4. \`$MIRROR_DIR/state/COREY_WORDS.md\` — vocabulary and philosophy" >> "$REPORT"
echo "5. \`$REPORT\` — this VPS lens report" >> "$REPORT"
echo "" >> "$REPORT"
echo "These files ARE the amnesia shield. Feed them first." >> "$REPORT"

echo ""
echo -e "${CYAN}═══════════════════════════════════════════${NC}"
echo -e "${CYAN} VPS LENS COMPLETE${NC}"
echo -e "${CYAN}═══════════════════════════════════════════${NC}"
echo ""
echo " Report:  $REPORT"
echo " Mirror:  $MIRROR_DIR/ ($MIRROR_COUNT files, $MIRROR_SIZE)"
echo ""
echo " State files pulled to: $MIRROR_DIR/state/"
echo " .env files pulled to:  $MIRROR_DIR/env/"
echo " Docs pulled to:        $MIRROR_DIR/docs/"
echo ""
echo " To use as amnesia shield:"
echo "   cat $MIRROR_DIR/state/SESSION_STATE.md"
echo "   cat $MIRROR_DIR/state/MASTER_HANDOVER.md"
echo ""
